name: Build Relying Party SDK

on:
  pull_request:
    types: [closed]
  push:
    branches: [ "develop", "dev", "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:       
    - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
    - uses: actions/checkout@v3
    - run: echo "The ${{ github.repository }} repository has been cloned."
    - run: echo "Setting up JDK" 
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Execute Gradle build
      run: ./gradlew --no-daemon dokkaHtml build

    - name: Store build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build artifcats
        path: |
            ./RelyingPartySdk/build/outputs/aar/RelyingPartySdk-*.aar
            ./RelyingPartySdk/build/outputs/aar/RelyingPartySdk-*.aar

    - name: Store documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: ./RelyingPartySdk/build/dokka/html/  
